Adding sub, mul, div function for bacardi test.
lunchclass/bacardi pull request #15
Opened 2017-08-19 16:18 UTC by chivalryko

We added sub, mul, div function to test bacardi project.
Then we will modulrization them with next patch.

Issue = #10

2017-08-19 16:46 UTC, romandev requested changes
Patch looks good to me but please update your name and email in AUTHORS file and then include it in this patch.

2017-08-20 07:02 UTC, chivalryko commented
Could you review it again ? : )

2017-08-20 11:11 UTC, romandev reviewed
In the commit description, should be ISSUE=#10

2017-08-20 11:11 UTC, romandev commented on AUTHORS
> +Byoungkwon Ko <bk_1.ko@samsung.com>
Why don't you use your personal email?

2017-08-20 11:11 UTC, romandev commented on examples/calculator.js
> +// <TODO:wrong value> assert.equal(calculator.sub(4.5878, 1.1234), 3.4644);
Should be TODO(your id or your name): Blah Blah. Please see: issue link.

2017-08-20 11:17 UTC, romandev approved these changes
LGTM

2017-08-20 11:18 UTC, merged